[package]
name = "driver_pact_tests"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
prost = "0.11.0"
prost-types = "0.11.1"

[dev-dependencies]
pact-plugin-driver = { version = "0.2", path = "../driver" }
expectest = "0.12.0"
env_logger = "0.10.0"
pact_consumer = "0.10.0"
async-trait = "0.1.52"
test-log = "0.2.11"
