name: Trigger update to docs.pact.io

on:
  # temp trigger by workflow_dispatch whilst testing
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs.pact.io update workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GHTOKENFORTRIGGERINGPACTDOCSUPDATE }}
          repository: pact-foundation/docs.pact.io
          event-type: pact-plugins-docs-updated
