[package]
name = "pact-plugin-driver-ffi"
version = "0.0.0"
edition = "2018"

[dev-dependencies]
pact-plugin-driver = { version = "0.3", path = "../driver" }
pact_ffi = "0.4.0"
env_logger = "0.10.0"
expectest = "0.12.0"
serde_json = "1.0.87"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
csv = "1.1.6"
prost = "0.11.2"
prost-types = "0.11.2"
test-log = "0.2.11"
tokio = { version = "1.23.0", features = ["full"] }
tonic = "0.8.2"
