[package]
name = "pact-plugin-driver-ffi"
version = "0.0.0"
edition = "2018"

[dev-dependencies]
pact-plugin-driver = { version = "0.1", path = "../driver" }
pact_ffi = "0.3.11"
env_logger = "0.9.0"
expectest = "0.12.0"
serde_json = "1.0.79"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "blocking", "json"] }
csv = "1.1.6"
prost = "0.11.0"
prost-types = "0.11.1"
test-log = "0.2.10"
tokio = { version = "1.18.2", features = ["full"] }
tonic = "0.8.0"
