[package]
name = "pact-plugin-cli"
version = "0.0.0"
edition = "2021"
authors = ["Ronald Holshausen <ronald.holshausen@smartbear.com>"]
description = "CLI utility for Pact plugins"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["pact"]
license = "MIT"
exclude = [
    "*.iml"
]

[dependencies]
pact-plugin-driver = "0.1.8"
clap = { version = "3.1.18", features = [ "derive" ] }
comfy-table = "5.0.1"
home = "0.5.3"
anyhow = "1.0.57"
serde_json = "1.0.81"
itertools = "0.10.3"
requestty = "0.3.0"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls-native-roots", "json", "stream"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"
os_info = "3.4.0"
indicatif = "0.16.2"
futures-util = "0.3.21"
sha2 = "0.10.2"
flate2 = "1.0"
