[package]
name = "csv-consumer-rust"
version = "0.0.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.4"
anyhow = "1.0.43"
csv = "1.1.6"

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.8"
pact_models = { version = "0.1", path = "../../../../pact-reference/rust/pact_models" }
pact_consumer = { version = "0.7", path = "../../../../pact-reference/rust/pact_consumer" }
pact_mock_server = { version = "0.7", path = "../../../../pact-reference/rust/pact_mock_server" }
serde_json = "1.0.66"
regex = "1.4.6"
fakeit = "1.1.1"
rand = "0.8.4"
tokio-test = "0.4.2"
