[package]
name = "csv-consumer-rust"
version = "0.0.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.4"
anyhow = "1.0.43"
csv = "1.1.6"

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.8"
pact_models = "0.2.0-beta.5"
pact_consumer = "0.8.0-beta.1"
pact_mock_server = "0.8.0-beta.2"
serde_json = "1.0.66"
regex = "1.4.6"
fakeit = "1.1.1"
rand = "0.8.4"
tokio-test = "0.4.2"
