[package]
name = "csv-consumer-rust"
version = "0.0.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11.4"
anyhow = "1.0.43"
csv = "1.1.6"

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.9.0"
pact_models = "0.4.5"
pact_matching = "0.12.11"
pact_mock_server = "0.9.3"
pact_consumer = "0.9.7"
pact-plugin-driver = "0.1.11"
serde_json = "1.0.66"
regex = "1.4.6"
fakeit = "1.1.1"
rand = "0.8.4"
test-log = "0.2.11"
