[package]
name = "protobuf-consumer-rust"
version = "0.0.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.43"
tonic = "0.6.2"
prost = "0.9.0"
prost-types = "0.9.0"

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.8"
pact_models = "0.3.3"
pact_consumer = "0.9.2"
pact-plugin-driver = { version = "0.1", path = "../../../drivers/rust/driver" }
serde_json = "1.0.66"
regex = "1.4.6"
fakeit = "1.1.1"
rand = "0.8.4"
maplit = "1.0.2"

[build-dependencies]
tonic-build = "0.6.2"
