[package]
name = "protobuf-consumer-rust"
version = "0.0.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.70"
tonic = "0.9.2"
prost = "0.11.0"
prost-types = "0.11.1"

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.10.0"
test-log = "0.2.11"
pact_models = "~1.1.4"
pact_consumer = "~1.0.1"
pact-plugin-driver = "~0.4.4"
serde_json = "1.0.95"
regex = "1.7.3"
fakeit = "1.1.1"
rand = "0.8.5"
maplit = "1.0.2"

[build-dependencies]
tonic-build = "=0.8.4"
