[package]
name = "pact-plugin-driver"
version = "0.0.1"
description = "Pact support library that provides an interface for interacting with Pact plugins"
edition = "2018"
documentation = "https://docs.rs/pact-plugin-driver"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
exclude = [
    "*.iml"
]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0",  features = ["derive"] }
anyhow = "1.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
home = "0.5.3"
log = "0.4.14"
tonic = "0.5.0"
prost = "0.8.0"
prost-types = "0.8.0"
tokio = { version = "1.0", features = ["full"] }
sysinfo = "0.20.0"
itertools = "0.10.1"
pact_models = { version = "0.2.0-beta.1", path = "../../../../pact-reference/rust/pact_models" }
regex = "1.4"
bytes = "1.0.1"
uuid = { version = "0.8.2", features = ["v4"] }
reqwest = "0.11.4"

[build-dependencies]
tonic-build = "0.5"
