[package]
name = "pact-plugin-driver"
version = "0.4.5"
description = "Pact support library that provides an interface for interacting with Pact plugins"
edition = "2021"
documentation = "https://docs.rs/pact-plugin-driver"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
exclude = [
    "*.iml"
]

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
backtrace = "0.3.67"
bytes = "1.4.0"
chrono = { version = "0.4.23", features = ["serde"], default-features = false}
flate2 = "1.0"
futures-util = "0.3.21"
home = "0.5.4"
indicatif = "0.17.2"
itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4.17"
maplit = "1.0.2"
md5 = "0.7.0"
os_info = "3.7.0"
pact_models = "~1.1"
prost = "0.11.8"
prost-types = "0.11.8"
regex = "1.7.3"
semver = "1.0.17"
serde_json = "1.0.95"
serde = { version = "1.0.159",  features = ["derive"] }
sha2 = "0.10.2"
sysinfo = "0.28.4"
toml = "0.7.2"
tokio = { version = "1.27.0", features = ["full"] }
tonic = "0.9.0"
tracing = { version = "0.1.37", features = [ "log" ] }  # This needs to be the same version across all the pact libs (i.e. pact ffi)
tracing-core = "0.1.30"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
uuid = { version = "1.3.0", features = ["v4"] }
zip = "0.6.2"

[dependencies.reqwest]
version = "0.11.16"
default-features = false
features = ["rustls-tls", "rustls-tls-native-roots", "json", "gzip", "deflate", "stream"]

[dev-dependencies]
env_logger = "0.10.0"
expectest = "0.12.0"
tempdir = "0.3.7"

[build-dependencies]
tonic-build = "0.9.0"

[profile.release]
# https://github.com/johnthagen/min-sized-rust
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
codegen-units = 1
panic = "abort"
lto = true