[package]
name = "pact-plugin-driver"
version = "0.5.1"
description = "Pact support library that provides an interface for interacting with Pact plugins"
edition = "2021"
documentation = "https://docs.rs/pact-plugin-driver"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
exclude = [
    "*.iml"
]

[features]
default = ["datetime", "xml"]
datetime = ["pact_models/datetime"] # Support for date/time matchers and expressions
xml = ["pact_models/xml"] # support for matching XML documents

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
backtrace = "0.3.69"
bytes = "1.5.0"
chrono = { version = "0.4.32", features = ["serde"], default-features = false }
flate2 = "1.0.28"
futures-util = "0.3.30"
home = "0.5.9"
indicatif = "0.17.7"
itertools = "0.12.0"
lazy_static = "1.4.0"
log = "0.4.20"
maplit = "1.0.2"
md5 = "0.7.0"
os_info = "3.7.0"
pact_models = { version = "~1.1.17", default-features = false }
prost = "0.12.3"
prost-types = "0.12.3"
regex = "1.10.3"
semver = "1.0.21"
serde_json = "1.0.111"
serde = { version = "1.0.195",  features = ["derive"] }
sha2 = "0.10.8"
sysinfo = "0.30.5"
tar = '0.4.40'
toml = "0.8.8"
tokio = { version = "1.35.1", features = ["full"] }
tonic = "0.10.2"
tracing = { version = "0.1.40", features = [ "log" ] }  # This needs to be the same version across all the pact libs (i.e. pact ffi)
tracing-core = "0.1.32"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
uuid = { version = "1.7.0", features = ["v4"] }
zip = "0.6.6"

[dependencies.reqwest]
version = "0.11.23"
default-features = false
features = ["rustls-tls-native-roots", "json", "gzip", "deflate", "stream"]

[dev-dependencies]
env_logger = "0.11.0"
expectest = "0.12.0"
tempdir = "0.3.7"

[build-dependencies]
tonic-build = "0.10.2"
