[package]
name = "pact-plugin-driver"
version = "0.1.7"
description = "Pact support library that provides an interface for interacting with Pact plugins"
edition = "2021"
documentation = "https://docs.rs/pact-plugin-driver"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
exclude = [
    "*.iml"
]

[dependencies]
serde_json = "1.0.81"
serde = { version = "1.0.137",  features = ["derive"] }
anyhow = "1.0.57"
lazy_static = "1.4.0"
maplit = "1.0.2"
home = "0.5.3"
tonic = "0.6.2"
prost = "0.9.0"
prost-types = "0.9.0"
tokio = { version = "1.18.1", features = ["full"] }
sysinfo = "0.21.2"
itertools = "0.10.3"
pact_models = "0.4.1"
regex = "1.5.5"
bytes = "1.1.0"
uuid = { version = "0.8.2", features = ["v4"] }
async-trait = "0.1.53"
os_info = "3.3.0"
md5 = "0.7.0"
semver = "1.0.9"
tracing = "=0.1.34"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
tracing-core = "=0.1.26"  # This needs to be the same version across all the pact libs (i.e. pact ffi)

[dependencies.reqwest]
version = "0.11.10"
default-features = false
features = ["rustls-tls", "rustls-tls-native-roots", "json", "gzip", "deflate"]

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.9.0"

[build-dependencies]
tonic-build = "0.6.2"
