[package]
name = "pact-plugin-driver"
version = "0.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
serde = { version = "1.0",  features = ["derive"] }
anyhow = "1.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
home = "0.5.3"
log = "0.4.14"
tonic = "0.5.0"
prost = "0.8.0"
prost-types = "0.8.0"
tokio = { version = "1.0", features = ["full"] }
sysinfo = "0.20.0"
itertools = "0.10.1"

[build-dependencies]
tonic-build = "0.5"
