[package]
name = "pact-plugin-driver"
version = "0.3.1"
description = "Pact support library that provides an interface for interacting with Pact plugins"
edition = "2021"
documentation = "https://docs.rs/pact-plugin-driver"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
exclude = [
    "*.iml"
]

[dependencies]
serde_json = "1.0.87"
serde = { version = "1.0.147",  features = ["derive"] }
anyhow = "1.0.66"
lazy_static = "1.4.0"
maplit = "1.0.2"
home = "0.5.4"
tonic = "0.8.3"
prost = "0.11.3"
prost-types = "0.11.2"
tokio = { version = "1.23.0", features = ["full"] }
sysinfo = "0.26.7"
itertools = "0.10.5"
pact_models = "^1.0"
regex = "1.7.0"
bytes = "1.2.1"
uuid = { version = "1.2.1", features = ["v4"] }
async-trait = "0.1.58"
os_info = "3.5.1"
md5 = "0.7.0"
semver = "1.0.14"
tracing = "0.1.37"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
tracing-core = "0.1.30"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
backtrace = "0.3.66"

[dependencies.reqwest]
version = "0.11.12"
default-features = false
features = ["rustls-tls", "rustls-tls-native-roots", "json", "gzip", "deflate"]

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.9.1"
tempdir = "0.3.7"

[build-dependencies]
tonic-build = "0.8.4"
