[package]
name = "pact-plugin-driver"
version = "0.4.7"
description = "Pact support library that provides an interface for interacting with Pact plugins"
edition = "2021"
documentation = "https://docs.rs/pact-plugin-driver"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
exclude = [
    "*.iml"
]

[features]
default = ["datetime", "xml"]
datetime = ["pact_models/datetime"] # Support for date/time matchers and expressions
xml = ["pact_models/xml"] # support for matching XML documents

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
backtrace = "0.3.69"
bytes = "1.5.0"
chrono = { version = "0.4.31", features = ["serde"], default-features = false }
flate2 = "1.0"
futures-util = "0.3.29"
home = "0.5.5"
indicatif = "0.17.7"
itertools = "0.12.0"
lazy_static = "1.4.0"
log = "0.4.20"
maplit = "1.0.2"
md5 = "0.7.0"
os_info = "3.7.0"
pact_models = { version = "~1.1.12", default-features = false }
prost = "0.11.9"
prost-types = "0.11.9"
regex = "1.10.2"
semver = "1.0.20"
serde_json = "1.0.108"
serde = { version = "1.0.193",  features = ["derive"] }
sha2 = "0.10.8"
sysinfo = "0.29.11"
tar = '0.4.40'
toml = "0.8.8"
tokio = { version = "1.35.0", features = ["full"] }
tonic = "0.9.2"
tracing = { version = "0.1.37", features = [ "log" ] }  # This needs to be the same version across all the pact libs (i.e. pact ffi)
tracing-core = "0.1.30"  # This needs to be the same version across all the pact libs (i.e. pact ffi)
uuid = { version = "1.6.1", features = ["v4"] }
zip = "0.6.6"

[dependencies.reqwest]
version = "0.11.22"
default-features = false
features = ["rustls-tls-native-roots", "json", "gzip", "deflate", "stream"]

[dev-dependencies]
env_logger = "0.10.1"
expectest = "0.12.0"
tempdir = "0.3.7"

[build-dependencies]
tonic-build = "0.9.2"
