[package]
name = "pact-plugin-driver"
version = "0.1.2"
description = "Pact support library that provides an interface for interacting with Pact plugins"
edition = "2021"
documentation = "https://docs.rs/pact-plugin-driver"
homepage = "http://www.pact.io"
repository = "https://github.com/pact-foundation/pact-plugins"
readme = "README.md"
keywords = ["testing", "pact", "cdc"]
license = "MIT"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
exclude = [
    "*.iml"
]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0",  features = ["derive"] }
anyhow = "1.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
home = "0.5.3"
log = "=0.4.14" # This needs to be the same version across all the pact libs (i.e. pact ffi)
tonic = "0.6.2"
prost = "0.9.0"
prost-types = "0.9.0"
tokio = { version = "1.0", features = ["full"] }
sysinfo = "0.21.2"
itertools = "0.10.3"
pact_models = "0.3.2"
regex = "1.5.4"
bytes = "1.1.0"
uuid = { version = "0.8.2", features = ["v4"] }
async-trait = "0.1.52"
os_info = "3.2.0"
md5 = "0.7.0"
semver = "1.0.6"
tracing = { version = "0.1", features = [ "log-always" ] }

[dependencies.reqwest]
version = "0.11.9"
default-features = false
features = ["rustls-tls", "rustls-tls-native-roots", "json", "gzip", "deflate"]

[dev-dependencies]
expectest = "0.12.0"
env_logger = "0.9.0"
pact_consumer = "0.9.0"

[build-dependencies]
tonic-build = "0.6.2"
