name: Pact Plugin Examples

on:
  - push
  - pull_request

jobs:
  examples:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Protobuf plugin
        run: scripts/ci-install-protobuf-plugin.sh
        shell: bash
      - name: Install csv plugin
        run: pact-plugin-cli install https://github.com/pact-foundation/pact-plugins/releases/tag/csv-plugin-0.0.2
        shell: bash
      - name: Run CSV examples
          run: |
            cd csv-consumer-jvm
            ./gradlew check
        shell: bash
        working-directory: examples/csv
