name: Pact Plugin Examples

on:
  - push
  - pull_request

jobs:
  csv-examples:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    env:
      PACT_DO_NOT_TRACK: true
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install plugin cli
        run: scripts/install-plugin-cli.sh
        shell: bash
      - name: Install Protobuf plugin
        run: ~/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
        shell: bash
      - name: Install csv plugin
        run: ~/bin/pact-plugin-cli -y install https://github.com/pact-foundation/pact-plugins/releases/tag/csv-plugin-0.0.3
        shell: bash
      - name: Install Pact verifier
        run: scripts/install-verifier-cli.sh
        shell: bash
      - name: Run CSV examples (Non-Windows)
        run: |
          set -e
          cd csv-consumer-jvm
          ./gradlew check
          cd ../csv-consumer-rust
          pact_do_not_track=true cargo test -- --test-threads 1
          cd ../csv-provider
          cargo build
          nohup ./target/debug/csv-provider &
          PID=$!
          trap "kill $PID" EXIT
          pact_do_not_track=true ~/bin/pact_verifier_cli -f ../csv-consumer-rust/target/pacts/CsvClient-CsvServer.json -p 8080
          pact_do_not_track=true ~/bin/pact_verifier_cli -f ../csv-consumer-jvm/build/pacts/CsvClient-CsvServer.json -p 8080
        shell: bash
        working-directory: examples/csv
        if: runner.os != 'Windows'
      - name: Run CSV examples (Windows)
        run: |
          set -e
          cd csv-consumer-jvm
          ./gradlew check
          cd ../csv-provider
          cargo build
          nohup ./target/debug/csv-provider &
          PID=$!
          trap "kill $PID" EXIT
          pact_do_not_track=true ~/bin/pact_verifier_cli -f ../csv-consumer-jvm/build/pacts/CsvClient-CsvServer.json -p 8080
        shell: bash
        working-directory: examples/csv
        if: runner.os == 'Windows'

  protobuf-examples:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    env:
      PACT_DO_NOT_TRACK: true
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Install plugin cli
        run: scripts/install-plugin-cli.sh
        shell: bash
      - name: Install Protobuf plugin
        run: ~/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
        shell: bash
      - name: Install Pact verifier
        run: scripts/install-verifier-cli.sh
        shell: bash
      - name: Install timeout on OSX
        run: |
          brew install coreutils
        shell: bash
        if: runner.os == 'macOS'
      - name: Run Protobuf examples
        run: |
          set -e
          cd protobuf-consumer-jvm
          ./gradlew check
          cd ../protobuf-consumer-rust
          pact_do_not_track=true cargo test
          cd ../protobuf-provider
          nohup go run main.go &
          PID=$!
          trap "kill $PID" EXIT
          timeout --foreground -s TERM 30s bash -c 'while [[ "$(curl -s -o /dev/null -m 3 -L -w ''%{http_code}'' -XPOST -d'{}' http://127.0.0.1:8111)" != "200" ]]; do echo "Waiting for http://127.0.0.1:8111" && sleep 2; done'
          pact_do_not_track=true ~/bin/pact_verifier_cli -f ../protobuf-consumer-rust/target/pacts/protobuf-consumer-rust-protobuf-provider.json -p 8111
          pact_do_not_track=true ~/bin/pact_verifier_cli -f ../protobuf-consumer-jvm/build/pacts/protobuf-consumer-protobuf-provider.json -p 8111
        shell: bash
        working-directory: examples/protobuf

  grpc-examples:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    env:
      PACT_DO_NOT_TRACK: true
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x
      - name: Install plugin cli
        run: scripts/install-plugin-cli.sh
        shell: bash
      - name: Install Protobuf plugin
        run: ~/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
        shell: bash
      - name: Install Pact verifier
        run: scripts/install-verifier-cli.sh
        shell: bash
      - name: Install timeout on OSX
        run: |
          brew install coreutils
        shell: bash
        if: runner.os == 'macOS'
      - name: Install Pact Go (Linux)
        run: |
          go install github.com/pact-foundation/pact-go/v2@2.x.x
          sudo $HOME/go/bin/pact-go -l DEBUG install
          sudo chmod 644 /usr/local/lib/libpact_ffi.so
          ls -la /usr/local/lib/
        shell: bash
        if: runner.os == 'Linux'
      - name: Install Pact Go (OSX)
        run: |
          go install github.com/pact-foundation/pact-go/v2@2.x.x
          $HOME/go/bin/pact-go -l DEBUG install
        shell: bash
        if: runner.os == 'macOS'
      - name: Install Pact Go (Windows)
        run: |
          go install github.com/pact-foundation/pact-go/v2@2.x.x
          #$HOME/go/bin/pact-go -l DEBUG install
          curl -L -o ~/.pact/pact_ffi.dll.gz https://github.com/pact-foundation/pact-reference/releases/download/libpact_ffi-v0.3.11/pact_ffi-windows-x86_64.dll.gz
          gunzip -N -f ~/.pact/pact_ffi.dll.gz
          cp ~/.pact/pact_ffi.dll examples/gRPC/area_calculator/consumer-go
          cp ~/.pact/pact_ffi.dll examples/gRPC/area_calculator/provider-go
        shell: bash
        env:
          PACT_GO_LIB_DOWNLOAD_PATH: .pact
        if: runner.os == 'Windows'
      - name: Run Protobuf examples
        run: |
          set -e
          set -x
          cd consumer-jvm
          ./gradlew check
          cd ../consumer-rust
          pact_do_not_track=true cargo test
          cd ../consumer-go
          pact_do_not_track=true go test
          cd ../provider-jvm
          cp ../consumer-jvm/build/pacts/* server/src/test/resources/pacts
          cp ../consumer-rust/target/pacts/* server/src/test/resources/pacts
          cp ../consumer-go/pacts/* server/src/test/resources/pacts
          ./gradlew check
          cd ../provider-go
          nohup go run provider.go > provider.go.out &
          PID=$!
          trap "kill $PID" EXIT
          PROVIDER_PORT=cat provider.go.out | cut -f4 -d:
          #timeout --foreground -s TERM 30s bash -c 'while [[ "$(curl -s -o /dev/null -m 3 -L -w ''%{http_code}'' -XPOST -d'{}' http://127.0.0.1:8111)" != "200" ]]; do echo "Waiting for http://127.0.0.1:8111" && sleep 2; done'
          pact_do_not_track=true ~/bin/pact_verifier_cli -f ../consumer-jvm/build/pacts/grpc-consumer-jvm-area-calculator-provider.json\
            -f ../consumer-rust/target/pacts/grpc-consumer-rust-area-calculator-provider.json\
            -f ../consumer-go/pacts/grpc-consumer-go-area-calculator-provider.json\
            -p $PROVIDER_PORT
        shell: bash
        working-directory: examples/gRPC/area_calculator
