name: Pact Plugin Examples

on:
  - push
  - pull_request

jobs:
  examples:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install plugin cli
        run: scripts/install-plugin-cli.sh
        shell: bash
      - name: Install Protobuf plugin
        run: ~/bin/pact-plugin-cli -y install https://github.com/pactflow/pact-protobuf-plugin/releases/latest
        shell: bash
      - name: Install csv plugin
        run: ~/bin/pact-plugin-cli -y install https://github.com/pact-foundation/pact-plugins/releases/tag/csv-plugin-0.0.2
        shell: bash
      - name: Install Pact verifier
        run: cargo install pact_verifier_cli
        shell: bash
      - name: Run CSV examples
        run: |
          set -e
          cd csv-consumer-jvm
          ./gradlew check
          cd ../csv-consumer-rust
          cargo test
          cd ../csv-provider
          cargo build
          nohup ./target/debug/csv-provider &
          PID=$!
          trap "kill $PID" EXIT
          pact_verifier_cli -f ../csv-consumer-rust/target/pacts/CsvClient-CsvServer.json -p 8080
          pact_verifier_cli -f ../csv-consumer-jvm/build/pacts/CsvClient-CsvServer.json -p 8080
        shell: bash
        working-directory: examples/csv
