name: Pact Plugin Driver (Gradle)

on:
  - push
  - pull_request

jobs:
  latest_jdk:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build plugin driver
      run: ./gradlew -s --no-daemon -i publishToMavenLocal
      working-directory: drivers/jvm
    - name: Build and install Protobuf plugin
      run: ./gradlew -s --no-daemon -i installLocal
      working-directory: plugins/protobuf
    - name: Run plugin driver tests
      run: ./gradlew -s --no-daemon -i check
      working-directory: drivers/jvm
    - name: Publish driver Pact file
      run: env
      working-directory: drivers/jvm
      if: runner.os == 'Linux'

  supported_jdks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 12, 13, 14, 15, 16 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build plugin driver
        run: ./gradlew -s --no-daemon -i publishToMavenLocal
        working-directory: drivers/jvm
      - name: Build and install Protobuf plugin
        run: ./gradlew -s --no-daemon -i installLocal
        working-directory: plugins/protobuf
      - name: Run plugin driver tests
        run: ./gradlew -s --no-daemon -i check
        working-directory: drivers/jvm
