name: Pact Plugin Driver (Rust)

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Protobuf plugin
        run: scripts/ci-install-protobuf-plugin.sh
        shell: bash
      - name: Build and install csv plugin
        run: |
          mkdir -p ~/.pact/plugins/csv-0.0.0
          cargo build
          cp pact-plugin.json target/debug/pact-csv-plugin* ~/.pact/plugins/csv-0.0.0/
        working-directory: plugins/csv
        shell: bash
      - name: Tests
        run: cargo test
        working-directory: drivers/rust/driver
        env:
          RUST_LOG: trace
          RUST_BACKTRACE: 1
      - name: FFI Tests
        run: cargo test -- --test-threads 1
        working-directory: drivers/rust/driver_ffi
        env:
          RUST_LOG: trace
          RUST_BACKTRACE: 1
      - name: Pact Tests
        run: cargo test
        working-directory: drivers/rust/driver_pact_tests
        env:
          RUST_LOG: trace
          RUST_BACKTRACE: 1
      - name: Build Components
        uses: marcopolo/cargo@master
        with:
          working-directory: drivers/rust
          command: build
      - name: Clippy
        uses: marcopolo/cargo@master
        with:
          working-directory: drivers/rust
          command: clippy
        if: runner.os == 'Linux'
      - name: Publish pact files
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.77/pact-1.88.77-linux-x86_64.tar.gz
          tar xzf pact-1.88.77-linux-x86_64.tar.gz
          VER=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          pact/bin/pact-broker publish -a "$VER+$GITHUB_SHA" -b https://pact-foundation.pactflow.io -k ${{ secrets.PACTFLOW_TOKEN }} target/pacts
        working-directory: drivers/rust/driver_pact_tests
        if: runner.os == 'Linux'

  musl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Protobuf plugin
        run: scripts/ci-install-protobuf-plugin.sh
        shell: bash
      - name: Build and install csv plugin
        run: |
          docker run --rm -v $(pwd):/workspace -v $HOME/.pact:/root/.pact \
           -w /workspace/plugins/csv -t  \
           -e 'RUST_LOG=debug' -e 'pact_do_not_track=true' \
           pactfoundation/rust-musl-build \
           -c 'mkdir -p ~/.pact/plugins/csv-0.0.0 && cargo build && cp pact-plugin.json target/debug/pact-csv-plugin ~/.pact/plugins/csv-0.0.0/'
      - run: |
         docker run --rm -v $(pwd):/workspace -v $HOME/.pact:/root/.pact \
           -w /workspace/drivers/rust/driver -t  \
           -e 'RUST_LOG=trace' -e 'pact_do_not_track=true' \
           pactfoundation/rust-musl-build \
           -c 'apk add protoc && cargo build && cargo test'
