name: Pact Plugin Driver (Rust)

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable, beta ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and install Protobuf plugin
        run: ./gradlew -s --no-daemon -i installLocal
        working-directory: plugins/protobuf
      - name: Tests
        uses: marcopolo/cargo@master # TODO: - use actions-rs/cargo@v1 when PR merged https://github.com/actions-rs/cargo/pull/59
        with:
          working-directory: drivers/rust
          command: test
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
      - name: Build Components
        uses: marcopolo/cargo@master
        with:
          working-directory: drivers/rust
          command: build
      - name: Clippy
        uses: marcopolo/cargo@master
        with:
          working-directory: drivers/rust
          command: clippy
      - name: Publish pact files
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.77/pact-1.88.77-linux-x86_64.tar.gz
          tar xzf pact-1.88.77-linux-x86_64.tar.gz
          VER=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          pact/bin/pact-broker publish -a "$VER+$GITHUB_SHA" -b https://pact-foundation.pact.dius.com.au -k ${{ secrets.PACTFLOW_TOKEN }}
        if: runner.os == 'Linux'

  musl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         docker run --rm -v $(pwd):/workspace -w /workspace/drivers/rust -t pactfoundation/rust-musl-build -c 'apk add protoc && cargo build && cargo test'
