name: Pact Plugin Driver (Rust)

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and install Protobuf plugin
        run: |
          ./gradlew -s --no-daemon -i installLocal
        working-directory: plugins/protobuf
      - name: Build and install csv plugin
        run: |
          mkdir -p ~/.pact/plugins/csv-0.0.0
          cargo build
          cp pact-plugin.json target/debug/pact-plugin-csv ~/.pact/plugins/csv-0.0.0/
        working-directory: plugins/csv
      - name: Tests
        run: cargo test
        working-directory: drivers/rust
        env:
          RUST_LOG: trace
          RUST_BACKTRACE: 1
      - name: Build Components
        uses: marcopolo/cargo@master
        with:
          working-directory: drivers/rust
          command: build
      - name: Clippy
        uses: marcopolo/cargo@master
        with:
          working-directory: drivers/rust
          command: clippy
        if: runner.os == 'Linux'
      - name: Publish pact files
        run: |
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.88.77/pact-1.88.77-linux-x86_64.tar.gz
          tar xzf pact-1.88.77-linux-x86_64.tar.gz
          VER=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          pact/bin/pact-broker publish -a "$VER+$GITHUB_SHA" -b https://pact-foundation.pact.dius.com.au -k ${{ secrets.PACTFLOW_TOKEN }} target/pacts
        working-directory: drivers/rust/driver
        if: runner.os == 'Linux'

  musl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and install Protobuf plugin
        run: ./gradlew -s --no-daemon -i installLocal
        working-directory: plugins/protobuf
      - run: |
         docker run --rm -v $(pwd):/workspace -v $HOME/.pact:/root/.pact \
           -w /workspace/drivers/rust -t  \
           -e 'RUST_LOG=debug' -e 'pact_do_not_track=true' \
           pactfoundation/rust-musl-build \
           -c 'apk add protoc openjdk11 && cargo build && cargo test -- --nocapture'
